### PR TITLE
Fixing only split depricated function 

### PR DESCRIPTION
**Pull request by sabbir1991**
Ok I just fixed only split() depricated functions to explode() functions.

### CODE REVIEW

**Comment by pbh-stu** [comment]
Good man I was about to do the same thing :) is there a clone of this repo i can include instead as the PR clearly isn't happening :)

**Comment by robations** [comment]
To be honest I'm shocked anyone's still using this. I'll take a look today — I was oversubscribed when this PR came in.

**Comment by robations** [comment]
Okay, that's merged, and dev-master should now reference the updated code in Packagist. Belated thanks to @sabbir1991 for the PR.

**Comment by pbh-stu** [comment]
We are using it on our Glove Site in the UK https://www.justgloves.co.uk for password resets, it's a laravel project. We are also in the same town as Intelli SMS :)

**Pull request merged**
